### ISSUE TITLE
Native addons doesnt work on build but works when I run it with nw app.nw

### ISSUE THREAD

**Issue by cmarrero01** [nwjs-community/nw-builder#124]
I have one native addons buil it with nw-gyp for 0.11.0 target and works perfectly when a run the app to test

```
nw app.nw
```

But, when I use node-webkit-builder and open myapp.exe the error is this:

```
Uncaught node.js Error
Error: no errorC:\Users\ADMINI~1\AppData\Local\Temp\nw1848_26155\node_modules\Hello.node
    at Error (native)
    at Module.load (module.js:354:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at window.require (<anonymous>:4:17)
    at load (app://familysafety/app.js:96:55)
    at exec (app://familysafety/app.js:110:9)
    at Object.getInfo (app://myapp/Device.js:11:9)
    at app://familysafety/main.js:21:19678
```

I check the version of node-webkit that node-builder use to build an is the same that I use to test.

Any suggest?

Best
C

**Comment by jbuiss0n** [comment]
Exactly the same error here.

Here is how i do:
1. Create my app (concat, uglify, etc....) in `./dist`
2. Run the task [grunt-node-webkit-builder](https://www.npmjs.com/package/grunt-node-webkit-builder), this creates me my `.exe` files
I then run the app.exe, and have the error `The specified module could not be found.
↵C:\Users\JRMY~1\AppData\Local\Temp\nw15744_7755\lib\greenworks-win64.node`.

But, when i do:
1. Create a zip from my `./dist`
2. Drag&Drop my app.zip on nw.exe
Everything is ok.

Do someone know what to do at this point ?

Thanks,

**Comment by cmarrero01** [comment]
Hi @jbuiss0n, no, I can't figured what happened with node-webkit-builder, I make my own grunt task that build my app, coping and ziping my app, etc.

**Comment by jbuiss0n** [comment]
@cmarrero01 Can you share your task ? I've tried manuelly to do it, but the output from the command `copy /b nw.exe+app.nw app.exe` give me an `app.exe` which do nothing...

Any advice at least ?

**Comment by yak1ex** [comment]
Hi. The same behavior occurs on my app and I may find the reason.

Native addon ( for the case of @cmarrero01 , Hello.node ) is dynamically-linked to nw.exe. However, the resultant executable by nwbuild usually its own different name. Thus loading the addon DLL will fail for the lack of the dependency. If you rename the resultant executable by nwbuild to nw.exe, it works (At least, it works on my environment). This is the reason why execution by original nw.exe also works.

Unfortunately, dependent DLL/EXE names are embedded in an addon DLL. So, I think It is not so easy to solve this issue. My just ideas are as follows: 
1. Patch import tables in addon DLLs (ugly and overkill?)
2. Separate nw.exe functions used by addon DLLs to a new fixed-name DLL (affect to nw.exe structure itself)

**Comment by yak1ex** [comment]
Sorry for noise. It has already been mentioned in https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp#known-issues-and-limitations and its linked issue.
