### ISSUE TITLE
Windows Executable properties are needed for enterprise deploy

### ISSUE THREAD

**Issue by frapporti** [nwjs-community/nw-builder#196]
When building for windows, the executable is missing some informations which are usually vital for enterprise deploy of the apps.

Those infos are the ones that can be accessed right-clicking the .exe, then choosing Properties > Details.
- File Description;
- Product Name;
- Version;
- Copyright;

There are workarounds using resource editors, but they are not very maintainable and they can very easily corrupt the executable.

**Comment by adam-lynch** [comment]
We use Anolis Resourcer via [winresourcer](https://www.npmjs.com/package/winresourcer) for the icon so maybe these properties could be edited with that too?

**Comment by adam-lynch** [comment]
@felicienfrancois, any idea?

**Comment by felicienfrancois** [comment]
it should be possible to to it with Anolis resourcer / winresourcer but it is not documented enough to make it trivial.
Even with the UI, I can't get it working.
The resourceType to use is "Version".

Something like that should do the job:
```javascript
require("winresourcer")({
    operation: "Add",
    exeFile: "path/to/the/file.exe",
    resourceType: "Version",
    resourceName: "1",
    lang: 1033,
    resourceFile: "path/to/a/file.bin" // ???
}, function(error) {
    // callback
});
```

But I can't figure out what should be the content of the resourceFile.
According to the documentation, anolis resourcer requires a file in input.
When extracting the data of an exe that already have version info, i get an empty file.
When trying to export the version info from the GUI, I get a raw binary file :S.

**Comment by felicienfrancois** [comment]
Well, I get it working with a file exported from the GUI.

What I made:
- Open Anolis resourcer GUI
- Open an exe which have Version info
- Export version info in a raw binary file `test.bin`
- Executed the following code:
```javascript
require("winresourcer")({
    operation: "Add",
    exeFile: "target.exe",
    resourceType: "Version",
    resourceName: "1",
    lang: 1033,
    resourceFile: "test.bin"
}, function(error) {
    // callback
});
```

And the target exe get the infos from the source exe.

Then, we now need to be able to creates this binary file programmatically.
Opening with a text editor and searching on the web, it seems that it is not really a binary file but a null-terminated string table (Unicode string with NULL characters `\u0000` between each characters and some special characters for key/pair and lines delimitation).

I'll search for a way to generate such a stringtable with nodejs

**Comment by adam-lynch** [comment]
Thanks for looking into this!


Regards,
Adam Lynch

**Comment by karldd** [comment]
@felicienfrancois Did you ever manage to get this working?

I did a little digging around and it looks we need to create a [VERSIONINFO](https://msdn.microsoft.com/en-us/library/windows/desktop/aa381058(v=vs.85).aspx) `.rc` file. For example like [this one](http://stackoverflow.com/a/3323786).

From there I believe it needs to be compiled into a binary `.res` file using [RC](https://msdn.microsoft.com/en-us/library/windows/desktop/aa381055(v=vs.85).aspx) with something like:
```
RC.Exe /v /fo outputFile.res inputFile.rc
```

Finally the `.res` file should be added using Anolis resourcer as you posted above. Unfortunately I haven't been able to get the properties to turn up. I'm guessing there is something amiss with the `.res` file I am generating.

**Comment by felicienfrancois** [comment]
@karldd I switched to electron (known as atom shell) so I no longer have thoose issues
To set versioninfo on electron binaries, I use [rcedit](https://github.com/atom/rcedit), which is also provided as a [node module](https://github.com/atom/node-rcedit) or a [grunt module](https://github.com/unindented/grunt-rcedit).

When I tried rcedit on NW.JS binaries, quite a long time ago, there was several issues (especially with the icon) but it may have changes as both NW.JS and rcedit have been updated.

In the case there are still issues with rcedit setting icon of nw.js, you may use winresourcer for the icon and rcedit for version info

**Comment by gpetrov** [comment]
this will be really handy feature to be able to change the version info automatically.

the icon can be changed now - but still not the file info

any progress?

**Comment by evshiron** [comment]
@gpetrov What about using `nwjs-builder` instead?

**Comment by gpetrov** [comment]
thanks @evshiron - wasn't aware of it - will check it out!
Is there a grunt module for it as well?

**Comment by evshiron** [comment]
@gpetrov I am afraid not. I have never used things like `grunt` or `gulp`. But I do make `nwjs-builder` callable from other node.js scripts (see "Use As Module" and "Manifest Options" sections of the README), maybe that helps if you want to compose a simple `grunt` task by yourself :)

**Comment by DblK** [comment]
I successfully added a way to edit windows executable information.
I wil make some tests and make a pull request soon.

Everything has been done with rcedit instead of winresourcer and work like a charm including icons (see below).
![image](https://cloud.githubusercontent.com/assets/832617/16564799/d5162b6a-4209-11e6-8204-51bb58787425.png)

**Comment by cdobbyn** [comment]
Not sure why someone hasn't posted this yet. Here's how to do it (from a gulp pleb) using [rcedit](https://www.npmjs.com/package/rcedit). This would be really nice to be able to do in nw-builder.

```
gulp.task('edit-nwjs', function(done) {
    version = '1.0.0';
    year = '2017';
    rcedit(
        './path/to/file.exe', 
        {
            'version-string': {
                'CompanyName': 'Your-Company-Here',
                'FileDescription': 'Description-About-Things',
                'LegalCopyright': 'Copyright ' + year + ' Your-Company-Here',
                'ProductName': 'Your-Product',
        },
        'file-version': version,
        'product-version': version,
    }, 
    done
    );
});
```

**Comment by MadLittleMods** [comment]
@cdobbyn When trying to change `FileDescription` via [`rcedit`](https://www.npmjs.com/package/rcedit) as a post-process to the `nw-builder` build, I would always get a blank/default-shimmer NW.js page when starting up the app instead of the specified `main` file. I suppose it is getting corrupted somehow 😕 

I made a PR to add it directly into the `nw-builder` package and do the `rcedit` before `winresourcer`, https://github.com/nwjs-community/nw-builder/pull/459 which is working great for me so far.

**Comment by evshiron** [comment]
Cool, when I did this I discovered that the appended bundle was stripped by `rcedit`, so call `rcedit` before appending should work.

**Comment by mscreenie** [comment]
Thanks @evshiron  . I decided to use nw-builder as it works pretty well with my automated building process. I'll look to see if I can fit nwjs-builder instead. I simply need to ship quickly, if not I may rcedit myself.
