### ISSUE TITLE
snapshot revisited

### ISSUE THREAD

**Issue by chino23** [nwjs-community/nw-builder#202]
Hi,

as of the release of nw 0.12.0, the snapshot functionality is stable, supports closure and runs like a charm. No comparison to the old 0.11.x and below.

As stated in https://github.com/mllrsohn/node-webkit-builder/issues/162, the thought was put away. But given the new development, it would be great to implement that as I use it for every build and I know a lot of others who make great use of it, given that it's dead stable and allows for secure deployment of the source code

**Comment by bhaveshgohel** [comment]
+1

**Comment by rodolfoag** [comment]
+1

**Comment by chino23** [comment]
is this supported now? @adam-lynch this is a pretty standard feature by now

**Comment by adam-lynch** [comment]
I know little about this. I can't seem to find new docs on it (it doesn't exist in the nwjs.io docs?). Is there any?

**Comment by ayushmxn** [comment]
@chino23 let me know of you want to get this discussion going again. I don't know much about snapshots but open to learn more.
