### ISSUE TITLE
"No such file or directory" after global installation

### ISSUE THREAD

**Issue by xingped** [nwjs-community/nw-builder#205]
I installed node-webkit-builder globally according to the instructions:

```
sudo npm install node-webkit-builder -g
```

but now I can't execute nwbuild no matter what I try. I just keep getting the error:

```
: No such file or directory
```

I even tried executing it directly from where it was stored (/usr/local/lib/node_modules/node-webkit-builder/bin/nwbuild) but no game. OS: Linux Mint 16. Any help?

Edit: This issue appears to have appeared before and seems to have assumed to have been resolved here: https://github.com/mllrsohn/node-webkit-builder/pull/105 , but this issue still appears.

Following a comment here: https://github.com/mllrsohn/node-webkit-builder/issues/75 I used vim to :set ff=unix and now it executes, but now when I use "nwbuild -v" or "nwbuild --version", it keeps spitting out the Usage text as if I'm using the command wrong.

**Comment by adam-lynch** [comment]
Sorry for the lack of a reply before. I'm going to close this optimistically. Please let me know if it's still an issue. Thanks.
