### ISSUE TITLE
How to use with node-webkit-updater in Linux?

### ISSUE THREAD

**Issue by pakastin** [nwjs-community/nw-builder#214]
Is it possible to produce `tar.gz` format for Linux, since [node-webkit-updater](https://github.com/edjafarov/node-webkit-updater#manifest-schema) seems to require it?

**Comment by adam-lynch** [comment]
Maybe node-webkit-updater should just be changed to support ZIPs for Linux? I'm not a Linux user but that shouldn't be a problem right?
