### ISSUE TITLE
Windows Load time

### ISSUE THREAD

**Issue by sbutalia** [nwjs-community/nw-builder#249]
When running on windows the initial load time of the app is 12 seconds. I double click the .exe and nothing happens for 12 seconds, then app loads.  On osx its instant. Any thoughts on what might be the cause?

Thanks!

**Comment by Baccanno** [comment]
It's because of zip compression in windows. The builder does not propose a non compressed version of windows builds yet

**Comment by benag** [comment]
any way to solve this? users wouldnt use it if it takes that long..

**Comment by thoughtspacewebsites** [comment]
Hmmm, definitely seems like an issue to me... I'm experiencing the same thing on my end. I don't even get any indication that load is happening, which causes repeated clicks of the app, and surely this will happen for end users too...

**Comment by sbutalia** [comment]
Turns out it is the size of the application and the # of files it compresses. 2 options are to use "zip: false" 
or minify all js files and use npm install --production

**Comment by adam-lynch** [comment]
I'm going to close this. If you're still fighting this, please see the [`zipOptions` option](https://github.com/nwjs-community/nw-builder#optionszipoptions) which allows you to tweak the compression level, etc.
