### ISSUE TITLE
`Info.plist` bundle identifiers are not adjusted on build

### ISSUE THREAD

**Issue by ripexz** [nwjs-community/nw-builder#257]
`nwjs Helper.app`, `nwjs Helper EH.app` and `nwjs Helper NP.app` Info.plist bundle identifiers are not changed, they remain as `io.nwjs.nw.helper` (+ `.NP` and `.EH` for the extra ones).

They should be adjusted to either the passed in param one or the default `com.nw-builder` with the .helper extras appended.

This has popped up a few times when validating for Mac App Store and can prevent apps from getting trough.

**Comment by adam-lynch** [comment]
@ripexz sounds like you know a lot more than me about this. Care to create a PR?

**Comment by ayushmxn** [comment]
@ripexz I know it's been a while but if this is still a blocker for publishing on App Store, we could fix this up pretty quick.

**Comment by ripexz** [comment]
@ayushmxn It has been a while indeed - I am no longer using nw.js so I'm not sure if it's still an issue and I don't have the time to investigate, I'll close it for the time being and if someone runs into it again they can reopen 😊
