### ISSUE TITLE
app cannot find main.js

### ISSUE THREAD

**Issue by adikari** [nwjs-community/nw-builder#302]
I have application that runs fine on the browser. When I use nw to build, it runs fine and works as expected. However when I package it using nw-builder, it somehow can not find the main.js. When I navigate to the directory where the nwjs app is, I can see the file there.

**nw-builder config**

```
var Builder = require('nw-builder');
var builder = new Builder({
  files: pathtofile + '/**/**',
  platforms: ['win64'],
  version: '0.12.3',
  cacheDir: '.cache',
  buildDir: 'build'
});
builder.build(function() {
  console.log('success');
});
```

Here everything works as expected. I have the build directory with all required files and executable.

build directory structure

```
-build
  -app.exe
  -main.js
  -index.html
```

In index.html the main.js is loaded as such.

`<script src="main.js"></script>`

When I load the app.exe, the app loads fine but in the console I have error saying:
`
Failed to load resource: net::ERR_FILE_NOT_FOUND file:///C:/main.js`

In the address bar of the application, the app is being loaded from:

`file:///C:/Users/MyHome~1/AppData/Local/Temp/nw141296_447/index.html`

PS:

`./node_modules/.bin/nw path_to_app`

Loads the app fine and everything is ok.

**Comment by adam-lynch** [comment]
Hmm strange. What's `pathtofile`?
