### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Vistritium** [nwjs-community/nw-builder#343]
when I try to build app:
`nwbuild .`
or run
`nwbuild -r .`
I get
`[TypeError: undefined is not a function]`
When I run in non-app folder it just says that it couldn't find package.json
I tried it on very simple app with just package.json and index.html, also tried it on another example app.
Is it possible to generate more logs so I could find more information about what is happening?
I use Windows 10

**Comment by carlgordon** [comment]
I'm getting the same error

**Comment by sn907635** [comment]
I'm getting the same error, but I fixed the bug temporarily.
in line 161 @ version.js
error code:
var version = versions.find(function(version){...});
fixed code:
var version = _.find(versions,function(version){...});

I use Mac:)

**Comment by adam-lynch** [comment]
Thanks for reporting. What's your Node version? nw-builder [requires version 4 or newer](https://github.com/nwjs/nw-builder/blob/master/package.json#L24).

**Comment by adam-lynch** [comment]
Ignore the fact this was closed above. I don't think that fixes your problem. I think it's related to an old Node version. But try 2.2.6 anyway and if it does fix your problem, I'll close this.

**Comment by adam-lynch** [comment]
Is this still a problem? We're now on 3.1.0 by the way.

**Comment by CaoMengLong** [comment]
if your node version is v0.12.xxxx  , you can use
`npm install node-webkit-builder -g`
and build it.

nw-builder mast less than V4.0 +
