### ISSUE TITLE
[BUG] "devDependencies" modules NOT IGNORED when zipping App

### ISSUE THREAD

**Issue by jhm-ciberman** [nwjs-community/nw-builder#348]
Steps to reproduce the bug:
1.  put "devDependencies" inside your package.json with all your desired dependences (including nw-builder itself)
2. Run `npm install`
3. Run `nwbuild --platforms win64 .\your_app\path`

In the log you can see how `\node_modules\nw-builder\...` and other modules that are only for a development environment are zipped, causing the final exe to be inflated with all those inservible modules.

**Comment by saitonakamura** [comment]
As an ugly workaround files key supports simple-glob format, so you can do `['.\your_app\path\**\**', '!.\your_app\path\node_modules\someDevDependency\**\**']`

**Comment by adam-lynch** [comment]
Yeah what you need to do is ignore them using a negative glob in your `files` parameter. 

We could add this too though. Pull-requests are welcome. I'm not sure exactly how it would work. We could only copy directories in `node_modules` which are in `dependencies` but this means if someone runs `npm i X` without the `--save` flag then we won't copy that dependency over into the app. This would not copy over any directories the user might have creating in node_modules themselves (although unlikely). We could delete not copy any directories in `node_modules` which match modules listed in `devDependencies` which *aren't also* in `dependencies`. Again this won't work if someone forgets the `--save-dev` flag.

I really don't want to annoy anyone here by breaking their existing usage and I also don't want to have to add an option for this 😄 .

**Comment by jhm-ciberman** [comment]
You can simply ignore the folders inside node_modules that are listed in
devDependencies. If some developer installs a dependency only for
development purposes it should be listed in devDependencies because by
default all packages not listed in the json are normal dependencies (not
dev).

**Comment by adam-lynch** [comment]
> You can simply ignore the folders inside node_modules that are listed in
devDependencies

I guess unless it's in both `dependencies` and `devDependencies` somehow.

>by default all packages not listed in the json are normal dependencies (not
dev).

Could you please explain what you mean here? Are you saying that if someone forgets `--save` or `--save-dev` then it must be a production dependency?

**Comment by saitonakamura** [comment]
> You can simply ignore the folders inside node_modules that are listed in
devDependencies

If dependencies was flattened, then it would only delete highest-level dependencies
Perhaps we should go over dependency tree branches, but that's tough cause some dependencies 
may be shared among dev and notDev. So basically we also want flatten dependency list, expect notDev from dev and ignore the remains

If list wan't flattened, then it's simple "ignore list of folders"

**Comment by adam-lynch** [comment]
You mean you're worried that the user might have `a` as a production dependency and `b` as a dev dependency but `a` also depends on `b`? Ugh yeah, this is getting complicated.

**Comment by jhm-ciberman** [comment]
Well, I am really new to ussing npm and lot of dependencies, so I don't
know how can I help.

**Comment by adam-lynch** [comment]
OK no problem

**Comment by evshiron** [comment]
Copy everything but `node_modules` to a temporary directory and `npm install --production` should be much easier to implement.

**Comment by jhm-ciberman** [comment]
Thanks!! You saved me.

**Comment by adam-lynch** [comment]
I've used https://github.com/Snyk/resolve-deps recently and it might help a lot here.

**Comment by bramblex** [comment]
I use following code to resolve deps by myself.

```JavaScript

    const deps = {}
    const resolve = p => {
      if (!deps[p]){
        deps[p] = true
        const p_deps = require(`${p}/package.json`).dependencies || []
        Object.keys(p_deps).forEach(function(p){
          return resolve(p)
        })
      }
    }

    resolve('..') // path to your project which include package.json file
    delete deps['..'] // delete root node

    // then just copy deps to your build dir
    Object.keys(deps).forEach(function(p){
      // copy ('node_modules/' + p) to ('<path to your build dir>/node_modules/' + p)

      // your can just use shelljs to cp dir
      require('shelljs/golobal')
      cp('-r', 'node_modules/' + p, '<path to your build dir>/node_modules/' + p)
    })

```

And here is a full example for my project [https://github.com/bramblex/nwjs-vue/blob/master/build/build.js#L52](https://github.com/bramblex/nwjs-vue/blob/master/build/build.js#L52)

**Comment by adam-lynch** [comment]
@bramblex nice.

Note: this only works with npm 3+

**Comment by tech4him1** [comment]
You could also add a build switch like `--cleanBuild` or `--production` so that people could choose if they wanted it packaged as is or copied and rebuilt like @evshiron said.

**Comment by tech4him1** [comment]
@adam-lynch What's the status on this, please?
