### ISSUE TITLE
Downloading custom binaries impossible because of checks

### ISSUE THREAD

**Issue by vankasteelj** [nwjs-community/nw-builder#372]
Hi

Since 2.0.2, you implemented some kind of check of the URL tree, making it, in my case where I host modified binaries elsewhere, impossible to use.

Here's the URL for Win32, for example: 

```
raw.githubusercontent.com/project/master/v0.12.2/nwjs-v0.12.2-win-ia32.zip
```

But because it checks `raw.githubusercontent.com/project/master/` before anything else, it fails, because `raw.githubusercontent.com/project/master/` sends back 400, where `raw.githubusercontent.com/project/master/v0.12.2/nwjs-v0.12.2-win-ia32.zip` does download the archive.

I'm stuck with 2.0.2 because of that. Maybe adding an option to remove the check, or making it optionnal, or even disabling it if `downloadUrl` is set would be a good idea.

Thanks

**Comment by adam-lynch** [comment]
Maybe we could add an option. Can I ask, why are hosting the versions yourself on GitHub?

**Comment by vankasteelj** [comment]
Because they're built using modified sources of the 0.12.2

**Comment by adam-lynch** [comment]
I think we're not going to go for this because support for legacy versions are deprecated. Thanks for suggesting anyway
