### ISSUE TITLE
Windows renamed application doesn't open using latest version (0.18.0) of nwjs

### ISSUE THREAD

**Issue by commanderfun** [nwjs-community/nw-builder#381]
Looks like nw-builder may not be "caught up" with nwjs on Windows. 

I ran a build using latest version of nwjs 0.18.0 and the app's main window fails to open. 

nwbuild -p "win64" .

I ran the same build with an earlier version of nwjs 0.17.4 and it works fine.

nwbuild -v "0.17.4" -p "win64" .

**Comment by chadams77** [comment]
This version of nwjs doesn't like the exe name being renamed, if you name it back to 'nw.exe' it'll run. I tried renaming 'nw.dll'  to '{myapp}.dll' instead and that didn't work, maybe I have to rename all the files prefixed 'nw' to '{myapp}.....'?

**Comment by EasyGitHub99** [comment]
Just built my app for win32 and win64. And they won't open until I change MyApp.exe into nw.exe

Hmm...

**Comment by DblK** [comment]
It is an issue, I reproduced in my configuration.
After fixing another issue I will try to find what causes the problem.

**Comment by adam-lynch** [comment]
😱 not https://github.com/nwjs/nw.js/issues/199 again

**Comment by adam-lynch** [comment]
@commanderfun I'm going to close this optimistically. Please let me know if it's still an issue, thanks.
