### ISSUE TITLE
Can't manual set prebuilt nw(sdk) path?

### ISSUE THREAD

**Issue by keyiis** [nwjs-community/nw-builder#383]
Because sdk download very slow,i want manual set sdk path to downloaded sdk,how to?

**Comment by keyiis** [comment]
Can disable connect 107.170.237.181?
it connect 107.170.237.181 when everytime i run “nwbuild -r app-path",although sdk downloaded.

**Comment by DblK** [comment]
I am not sure without any additional information but if you have "latest"
for your version it will check online but if you replace this by "0.18.0"
and flavor "sdk" it won't check online.

Hope that solve your problem.

**Comment by keyiis** [comment]
@DblK I am not set version and flavor,
```
var NwBuilder = require('nw-builder');
gulp.task("nw:build", ()=> {
    var nw = new NwBuilder({
        files: helpers.outputBuild('/**/**'),
        buildDir: helpers.outputNwDist(),
        cacheDir:'src/desktop/nw/cache',
        platforms: ['win64'],
        winIco:helpers.outputBuild("icon.ico")
    });
    nw.on('log', console.log);
    // Build returns a promise
    return nw.build();
});
```

**Comment by DblK** [comment]
Thanks for you reply.
If you use the default value, which is the case, as you quoted from the documentation, the version is set to "latest".
The latest version isn't a number like 0.18.2 (which is the latest right now), so nw-builder has to perform a check to know which number is the latest version over internet before checking the cache.
If you set a specific version that match you cache, you can avoid the connexion to the remote server.
