### ISSUE TITLE
Command line "-p" does not work

### ISSUE THREAD

**Issue by Naiba01** [nwjs-community/nw-builder#387]
I ran this `nwbuild -p win32 -v 0.14.7 -r .` in command line.
It is expected to use **win-x32** version.
But actually it downloaded the **win-x64** version.Is it an unresolved problem?

**Comment by fleskesvor** [comment]
I'm having the same issue trying to build for linux64. I haven't dug into the source, but it seems to expect downloads from http://dl.nwjs.io/ to have the given platform(s) as part of the filename, while those are named *-linux-x64.tar.gz, etc. However, trying to build with linux-x64 as platform is an error.

**Comment by adam-lynch** [comment]
Thanks for reporting. It always used the current platform when `-r` is used. This is fixed in 3.2.2.
