### ISSUE TITLE
Run linux app after builded

### ISSUE THREAD

**Issue by sanderique** [nwjs-community/nw-builder#411]
Sorry everyone for my stupidity,
But what do I do after building the linux64 app?

I built the app for linux 64  with normal nw version 0.19.2.

Apparently everything is ok, I don't know how to run the app though.

You can see the generated files bellow.

![screenshot_2016-12-20_21-50-14](https://cloud.githubusercontent.com/assets/24585437/21352852/5f1f2748-c6fe-11e6-812a-29486562c693.png)

Thanks in advance for the help.

**Comment by bil-elmoussaoui** [comment]
Just use your terminal and go the current directory, run `chmod +x ./panel_p2` and after that, `./panel_p2` which will run the application.

**Comment by nathpaiva** [comment]
I have a question about Linux distribution, how can I package to delivery for my clients?

I need to pack of .deb?

**Comment by adam-lynch** [comment]
This looks resolved. Closing.

@nathpaiva you could ship a ZIP, `.deb` like you said (although nw-builder doesn't handle that for you), publish your app to Linux package managers, etc.
