### ISSUE TITLE
Startup performance optimization

### ISSUE THREAD

**Issue by julmot** [nwjs-community/nw-builder#421]
I'm curious if it's necessary to zip the entire project into one exe? If I remember correctly Electron just copies the project – not as zip. I'm asking because https://github.com/nwjs/nw.js/issues/514 documents some significant performance issues that I'm also experiencing on Windows. My app needs about 40-45 seconds to start – with no visual progress bar. It seems to occur due to the `node_modules` folder which in my case is about 700 MB large with 12,698 files. I'm also having 14 video files with a size of 255 MB, but even without them it's only 5 seconds faster.

**Comment by DzikuVx** [comment]
I second this request

**Comment by Arti3DPlayer** [comment]
+1

**Comment by adam-lynch** [comment]
You can disable the zipping for Windows builds using the [`zip` option](https://github.com/nwjs-community/nw-builder#optionszip). You can also customizable the compression level, etc. using the [`zipOptions` option](https://github.com/nwjs-community/nw-builder#optionszipoptions).

I'm going to close optimistically (I'm doing a bit of a triage now). Let me know if those options aren't enough. Thanks.
