### ISSUE TITLE
why do this,though my cache has the nw version file,  code: 'ETIMEDOUT',

### ISSUE THREAD

**Issue by Vincent2015** [nwjs-community/nw-builder#422]
[08:39:25] Starting 'nw'...
[08:40:43] nw-builder { Error: connect ETIMEDOUT 107.170.237.181:80
    at Object.exports._errnoException (util.js:896:11)
    at exports._exceptionWithHostPort (util.js:919:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1073:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '107.170.237.181',
  port: 80 }

**Comment by wangyinlong** [comment]
I have the same question

**Comment by adam-lynch** [comment]
Is this when you don't have a connection is it?

**Comment by cssxn** [comment]
I have the same

**Comment by yeyu456** [comment]
the same

**Comment by cssxn** [comment]
@yeyu456 @wangyinlong @Vincent2015   I solved the problem that you'd better download the https://nwjs.io/versions.json  and put it on your own website, and set the url to  NWBuilder parameter

-- manifestUrl  'YourURL'

**Comment by adam-lynch** [comment]
Thanks for reporting but I'm closing this as a duplicate of #419.
