### ISSUE TITLE
Flavor per platform or option for OSX to set it to `mas`

### ISSUE THREAD

**Issue by ripexz** [nwjs-community/nw-builder#423]
I'm building `normal` for Windows/Linux but then need another instance to build `mas` flavor for OSX.

Using `platformOverrides` might be confusing since it's intended for the manifest, but perhaps a `macUseMASFlavor: true/false` option that overrides provided `flavor` could be added?

EDIT: Looks like there's a different download URL for MAS flavor now, available again from 0.19.5 onwards, I guess they need to sort out their publishing issues before this can be done.

**Comment by flippyhead** [comment]
Running into this problem myself. I don't think the mas build is any different structurally from the other builds so if it was possible to just download it myself and place it somewhere nwbuild can use it, could that work?

**Comment by ripexz** [comment]
@flippyhead You can put it in the cache folder, as long as the folder structure is the same as `nw-builder` expects, should work fine.

**Comment by adam-lynch** [comment]
Sorry @ripexz, closing because I don't see MAS builds for recent versions; https://nwjs.io/versions.json.
