### ISSUE TITLE
'flavor' option does not work for me

### ISSUE THREAD

**Issue by varshneyjayant** [nwjs-community/nw-builder#440]
I am setting flavor as `normal` still gulp is downloading the sdk version of nw-js. 

` flavor : 'normal',`

**Comment by CareyJWilliams** [comment]
Seconded. I took a very brief look at the nw-builder module (v 3.2.0) and the files don't seem to be at all inline with the git repository. All the flavour code is missing from Version.js for example.

**Comment by varshneyjayant** [comment]
I updated to latest version 3.2.0, seems to be working for me now.
