### ISSUE TITLE
Any way to add `nw` parameters not meant for chrome executable?

### ISSUE THREAD

**Issue by codekiln** [nwjs-community/nw-builder#441]
I have a node-webkit app that requires a specific chrome extension. As a result, I must start it with `nw --load-extension='path/to/extension'` [as mentioned in nw.js's documentation](http://docs.nwjs.io/en/latest/For%20Users/Debugging%20with%20DevTools/#using-devtools-extensions). Is there a way for me to add the `--load-extension` call to the generated script? It is important to note that this is an argument meant for node webkit, not for chromium, so I cannot put it in the chromium args parameter in the manifest.

**Comment by adam-lynch** [comment]
Hmm as far as I know, no. The generated app is the same as any other NW.js app, so you'd have to manually run the app with that argument, just like the docs say there. Which platforms do you need to support? On Windows, you could create a shortcut which when ran, runs your app with that argument. So you'd need to ship that shortcut with your app and make sure it's in the correct locations (so the user will definitely run that, not the actual app). For other platforms, something similar might be possible via some form of shortcut or a script, but I'm not sure :/. 

There might be a way to load it at runtime if you wrote a [native module](https://nodejs.org/api/addons.html) which called a Chromium method. This is assuming that an extension can be loaded at runtime (in Chrome they can be anyway). I haven't done something like this myself though. Maybe it's worth asking over on the NW.js issue tracker if it's possible to load an extension at runtime. Even if not, they might add an NW.js API method which would allow for that.
