### ISSUE TITLE
builder 3.2.3 doesn't work with 0.22.3 sdk

### ISSUE THREAD

**Issue by Arti3DPlayer** [nwjs-community/nw-builder#449]
Still have issue like this: https://github.com/nwjs-community/nw-builder/issues/445  with `0.22.3 sdk` and `"nw-builder": "^3.2.3"`. On normal flavor works good

**Comment by adam-lynch** [comment]
@Arti3DPlayer delete your cache and try again. A bug resulted in something broken being cached before 3.2.3. Let me know if there's anything wrong, thanks.
