### ISSUE TITLE
Cannot find 'sqlite3' module after building

### ISSUE THREAD

**Issue by kralkurt** [nwjs-community/nw-builder#461]
nw 0.19.5
nw-builder 3.1.3
sqlite3 3.1.8

the sqlite3 module works like a charm when I use:
` nw /src `

however after building the .exe file using:
`nwbuild --platforms win32,win64 --buildDir dist/ src/`

The screen where the info recovered from the DB is blank and when I open the devTools I get the following error:

> Uncaught Error: Cannot find module 'sqlite3'
at Function.Module._resolveFilename (module.js:509:15)
at Function.Module._load (module.js:456:25)
at Module.require (module.js:537:17)
at require (internal/module.js:11:18)
at self.require (<anonymous>:11:26)
at self.require (<anonymous>:11:26)
at chrome-extension://ojgfnihaaaghaeillanojiaedfdpbanh/app/gameSys.js:5:15

I built the sqlite3 module for node-webkit & for that specific version.

**Comment by adam-lynch** [comment]
Could you please supply an example project?

**Comment by FredericGuilbault** [comment]
Try   `  -v 0.31.0 ` nw and sqlite have a version compatibility problem. I foundout that 31 was working with current version of sqlite module .
