### ISSUE TITLE
Deprecation warning - Archiver.bulk()

### ISSUE THREAD

**Issue by Blatman** [nwjs-community/nw-builder#462]
OSX 10.11.6 El Capitan

Came across this warning -
Archiver.bulk() deprecated since 0.21.0
during my hackabout with nw-builder - not sure if it is the best way to fix it but I have used archive.glob successfully.
The essential line is -
archive.glob('\*\*/\*\*', { nodir: true, cwd: srcFold });
I have attached a wee text file outlining the full workround (at the bottom) but there is a whole lot of other stuff that may be of use to some nw-builder users.

[nwbhack.txt](https://github.com/nwjs-community/nw-builder/files/1188896/nwbhack.txt)

Updated txt file - may be of use to hack nwb since the project does appear to be struggling for maintainers.

Cheers.

**Comment by simkea** [comment]
please replace the following call:
FILE: /lib/utils.js LINE: 167
   archive.bulk(filesBulk);

with the new solution 
e.g. archive.glob(...,{},...);

br, thx

**Comment by adam-lynch** [comment]
OK thanks. I'd really appreciate if someone could [submit a pull-request](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) for this 👍

**Comment by simkea** [comment]
It is strange that this warning does not appear in this project nw-builder-bin.
https://www.npmjs.com/package/nw-builder-bin

**Comment by piwonesien** [comment]
@kessler This should be fixed in 3.5.2
