### ISSUE TITLE
nw builder generate totally incorrect app structure for osx

### ISSUE THREAD

**Issue by Arti3DPlayer** [nwjs-community/nw-builder#464]
I'm using nw-builder `3.2.3`. After build and sign in i got rejection from app store:

```
ERROR ITMS-90296: "App sandbox not enabled. The following executables must include the "com.apple.security.app-sandbox" entitlement with a Boolean value of true in the entitlements property list: [( "com.codeorangeinco.raceflight.pkg/Payload/rf.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/Helpers/crashpad_handler", "com.codeorangeinco.raceflight.pkg/Payload/rf.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/Resources/app_mode_loader.app/Contents/MacOS/app_mode_loader", "com.codeorangeinco.raceflight.pkg/Payload/rf.app/Contents/Versions/59.0.3071.115/nwjs Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/MacOS/AlertNotificationService" )] Refer to App Sandbox page at https://developer.apple.com/devcenter/mac/app-sandbox/ for more information on sandboxing your app."
```
![screen shot 2017-07-31 at 01 19 24](https://user-images.githubusercontent.com/3278913/28757556-55befae0-758e-11e7-8346-84585a944c78.png)

Then i tried to sign app from MAS example nw.js app:

http://dl.nwjs.io/v0.19.5-mas-beta/

![screen shot 2017-07-31 at 01 18 17](https://user-images.githubusercontent.com/3278913/28757550-3b7078d0-758e-11e7-95c0-5700501d0d9b.png)

It works well. Here is apple guide:

https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html

**Comment by Arti3DPlayer** [comment]
ah I'm sorry, i think with this all is alright) But app still wont sign:(

**Comment by Arti3DPlayer** [comment]
According to this issue:
https://stackoverflow.com/questions/45191194/unsealed-contents-present-in-the-root-directory-of-an-embedded-framework/45835046?noredirect=1#comment78714100_45835046

Something wrong with nw builder generated structure, but I can't figure out what exactly:( MAS sign not working

**Comment by adam-lynch** [comment]
I'm afraid I don't know much about getting an NW.js app into the Mac App Store. Could you tell me what the options you're passing to nw-builder are?

**Comment by Arti3DPlayer** [comment]
@adam-lynch I spent a week to figure out this. But nothing helped:( https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html

Try to use MAS if you have developer account

http://docs.nwjs.io/en/latest/For%20Users/Advanced/Support%20for%20Mac%20App%20Store/

**Comment by adam-lynch** [comment]
Ugh I'm sorry. 

>Try to use MAS if you have developer account

I don't I'm afraid. Your best bet might be to ask here (https://groups.google.com/forum/#!forum/nwjs-general) for suggestions because someone there might have done it.

**Comment by ayushmxn** [comment]
@Arti3DPlayer let me know if this issue happens with one of the latest versions such as v63 or v64
