### ISSUE TITLE
Packaging app for Linux

### ISSUE THREAD

**Issue by Frontrider** [nwjs-community/nw-builder#465]
I can not figure out how to do that. The structure seems to be wrong, and whatever I did so far was incorrect...

I want to get a deb and/or an appimage file out of the result.
(one of them should be included by default tough. Ubuntu makes debian a good option, if not appimage can run on any system.)

Any ideas?

**Comment by adam-lynch** [comment]
I've never actually published a Linux version to a package manager, I'm not sure which package managers the structure supports. I'm open to say supporting AppImage but I'd need help to get there, be that via comments here or preferably a [pull-request](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

**Comment by EthraZa** [comment]
Don´ t know if it helps in this case, but [Checkinstall](https://wiki.debian.org/CheckInstall) helped me to generate .rpm and .deb packages in the past, it is really very easy to use. You just create a dumb makefile that only cp your files somewhere in the system and run checkinstall to make it an installable package.

**Comment by kessler** [comment]
@Frontrider closing this issue. If, in the meantime, you found a solution to your packaging problem and care to update here so others can enjoy it  that would be awesome.
