### ISSUE TITLE
builder corrupts nw app if version 0.25.0-sdk

### ISSUE THREAD

**Issue by Ajeey** [nwjs-community/nw-builder#470]
I am trying to build with version - 0.25.0-sdk
After its all done, I unzip and try to run the app, I get a crash screen!

**Comment by adam-lynch** [comment]
Sorry to hear. Which platform are you building for? And on what OS? Is it the latest version of NW.js? And does it happen for a Hello World app?

**Comment by kessler** [comment]
closing due to staleness
