### ISSUE TITLE
Can't Build in nw.js 0.25.0

### ISSUE THREAD

**Issue by saravanans-arch** [nwjs-community/nw-builder#472]
errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'C:\\Users\\AppData\\Roaming\\npm\\node_modules\\node-webkit-
builder\\cache\\0.25.0\\win32\\ffmpegsumo.dll' }

Can't build simple application using nw.js. I was done all the solution for this error. But still i'm facing this issue. Any one please help.

**Comment by adam-lynch** [comment]
I just tried it here on my Mac and it was fine. Is this still a problem for you? I can try it on a Windows machine when I get a chance

**Comment by kessler** [comment]
closing due to staleness
