### ISSUE TITLE
wrong osx64 shortcuts 

### ISSUE THREAD

**Issue by moto-hastam-zz** [nwjs-community/nw-builder#473]
When I use nw-builder in command line like `sudo nwbuild -p osx64 ./` it's working fine but when I use grunt plugin osx64 shortcuts are wrong.

**Comment by adam-lynch** [comment]
What do you mean by shortcuts?

**Comment by kessler** [comment]
@motohastam is this still an issue?

**Comment by ayushmxn** [comment]
@moto-hastam-zz this is probably an issue with the grunt plugin. I plan to make a release by next week after which I'll work on the grunt plugin.
