### ISSUE TITLE
macOS unidentified developer on update

### ISSUE THREAD

**Issue by Style87** [nwjs-community/nw-builder#475]
I've written my app and added an exception so it can run because it wasn't from the app store. However on update I get the error below. Is there any way around this issue when updating on macOS without paying Apple $99 for a Developer ID?
<img width="429" alt="screen shot 2017-10-01 at 9 38 30 am" src="https://user-images.githubusercontent.com/670897/31056811-f34bcfb6-a68c-11e7-8b30-fa3027926d3b.png">

**Comment by adam-lynch** [comment]
The second line in the dialog seems to imply you can allow it by changing your security preferences.

Also, I could be wrong but isn't there a way around this like right clicking the app then clicking Open (or something like that)?

**Comment by Style87** [comment]
You can probably get around it by changing your security settings and you can open it by going to the mac settings > security and clicking a button there. Since this is software made for developers this should be fine but I'd like to make software in the same way for non-developer users. Requiring anything extra from a regular user typically ends in failure.

**Comment by kessler** [comment]
@Style87 You need to be an apple developer, start here: https://developer.apple.com/programs/
