### ISSUE TITLE
How to separate the NW framework and the HTML&JS&CSS(folder static) with Windows when `zip = true`

### ISSUE THREAD

**Issue by tangyue0924** [nwjs-community/nw-builder#479]
If set the `zip: true` in Windows platform;
The folders and files  `node_modules`, `index.html`, `package.json`, `static` will be merged into `${name}.exe`;
If I don't want to merge some specific folders like `static/`, how should I set it?

**Comment by adam-lynch** [comment]
The `files` option should be enough here. See the description in the README: https://github.com/nwjs-community/nw-builder#optionsfiles-required. The one starting with `!` is excluded.
