### ISSUE TITLE
archive.bulk is not a function

### ISSUE THREAD

**Issue by Ctaque** [nwjs-community/nw-builder#481]
Hi,
As noticed in two issues, archives.bulk is deprecated and has been removed from node-archiver:

2.0.0 — July 5th, 2017 — Diff
change: removal of deprecated bulk functionality. (#249)

[sources](https://archiverjs.com/docs/)

It results as a build error:

`
TypeError: archive.bulk is not a function
    at /usr/local/lib/node_modules/nw-builder/lib/utils.js:167:21
    at Object.generateZipFile (/usr/local/lib/node_modules/nw-builder/lib/utils.js:140:16)
    at Promise.then.zipPromises (/usr/local/lib/node_modules/nw-builder/lib/index.js:528:23)
    at /usr/local/lib/node_modules/nw-builder/lib/index.js:526:9
    at NwBuilder.zipAppFiles (/usr/local/lib/node_modules/nw-builder/lib/index.js:517:12)
`

**Comment by bastimeyer** [comment]
nw-builder doesn't use archiver 2.x:
https://github.com/nwjs-community/nw-builder/blob/3.5.1/package.json#L48

The version range `^x.y.z` is equivalent to `>=x.y.z <(x+1).0.0`:
https://github.com/npm/node-semver#caret-ranges-123-025-004

**Comment by Ctaque** [comment]
Ok, thanks. archiver is installed globally in my system due to the config of the project I work on. Not sure if I can change the version. So I switched from archive.bulk to archive.blob() and I have no compilation error but the compiled project is empty (I see only a  black screen with nw.js title when I lauch the app, windows or linux.)
