### ISSUE TITLE
Print dialog is always in English in MacOS build

### ISSUE THREAD

**Issue by artemnikotin** [nwjs-community/nw-builder#485]
Hi, I have a problem with print dialog language in osx build. Seems osx build does not support any locales except english one.

NWJS Version : 0.29.1
Operating System : MacOS 10.13.3
nw-builder Version : 3.5.1

Expected behavior
// this values I have in Chrome browser running on this OS and in original NWJS application
window.navigator.languages; // ["ru", "en-US", "en"]
window.navigator.language; // "ru"

Actual behavior
window.navigator.languages; // ["en-US", "en"]
window.navigator.language; // "en-US"

Details
My windows build shows print dialog in Russian, but MacOS build always shows dialogs in English, although, as I can see, other locales can be found in built application at "XXX.app\Contents\Versions\65.0.3325.162\nwjs Framework.framework\Versions\A\Resources".
Seems this problem related to #357 
Can please somebody help?

**Comment by Blatman** [comment]
Maybe this is not the fault of NWB - I just checked the InfoPlist.strings files in the nwjs 0.29 and 0.30 versions and all the locales seem to be in English - 0.28 and earlier are fine so it may pay to file a bug report with the nwjs repository - https://github.com/nwjs/nw.js/issues.
Cheers.

**Comment by artemnikotin** [comment]
@Blatman Hi. Thanks for your comment. Unfortunately I can't use your patch cause _InfoPlist.strings_ files in each locale directory contains _nwjs_ as application name and MacOS shows this name in finder. So we can either change "CFBundleDisplayName" to the application name in each _InfoPlist.strings_ or just simply create empty directories with names "{locale}.lproj". For some reason this work for me. So this "hack" fix problem with:
- window.navigator.languages
- window.navigator.language
- print dialog language
