### ISSUE TITLE
NW builer within a nwjs app.

### ISSUE THREAD

**Issue by vairabagni** [nwjs-community/nw-builder#486]
I want to make a desktop app using nwjs using which end user will create their own desktop app by uploading some html web page. How can I embed this builer inside my desktop app. If I simply specify this as a dependency into app the exe file size is increasing which I don't want. Any idea?

**Comment by kessler** [comment]
@vairabagni IMHO, this question is a little bit too wide to be an issue. We can't try to assist you with the file size issue if you can post some relevant details.

Closing this issue for now.
