### ISSUE TITLE
Cannot install - permission denied

### ISSUE THREAD

**Issue by joshmbg** [nwjs-community/nw-builder#487]
I am running as root - it should be impossible for any permissions to be denied; root can access any file on the system. Installing anything else works; there must be something specific to nw-builder that is preventing it from being installed.

```
~$ npm install nw-builder -g
npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/adam-lynch/node-temp.git
npm ERR!
npm ERR! fatal: Unable to read current working directory: Permission denied
npm ERR!
npm ERR! exited with error code: 128
```

**Comment by joshmbg** [comment]
I believe the problem is due to the git repository. Trying to manually run `/usr/local/bin/git ls-remote -h -t ssh://git@github.com/adam-lynch/node-temp.git` (which is the command npm is running, as shown in the logfile) produces an error:

```
~$ /usr/local/bin/git ls-remote -h -t ssh://git@github.com/adam-lynch/node-temp.git
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by kessler** [comment]
@joshmbg do you have MFA enabled on your github account?

**Comment by kessler** [comment]
@joshmbg thanks for the update!
