### ISSUE TITLE
Issue with globbing hidden files?

### ISSUE THREAD

**Issue by nwittwer** [nwjs-community/nw-builder#491]
Expectation: 
All files defined in `files` (incl. hidden) will be placed into the final Mac app that this plugin builds

Actual result:
Hidden files are not copied to the final app

Here is my Gulp usage:
```
var nw = new NwBuilder({
    version: '0.30.3',
    files: [
      'src/**/*'
    ],
    platforms: ['osx64']
  });

return nw.build();
```

Everything else works great, just having issues getting hidden files to show up. Does it sound like an issue with the glob pattern I'm using, or related to nw-builder?

**Comment by kessler** [comment]
@nwittwer In most linux flavors I know globbing does not match hidden files automatically. I also had a quick look in gnu's manuals:

> When a pattern is used for filename expansion, the character ‘.’ at the start of a filename or immediately following a slash must be matched explicitly, unless the shell option dotglob is set. When matching a filename, the slash character must always be matched explicitly. In other cases, the ‘.’ character is not treated specially.

(from: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html)

I suspect it's not a desired default behavior to move all hidden files implicitly. I suggest you add a separate expression for hidden files (I think it's `src/**/.*`)
