### ISSUE TITLE
Does it protect source code?

### ISSUE THREAD

**Issue by oL-web** [nwjs-community/nw-builder#493]
Hey. I'm wondering if building an app with nw-builder protects the source code. NW unlike Electron supports that option using snapshots and nwjc. I haven't looked at how all of this works yet but I know it's an option. There are two .bin files in the build directory. Is that it or is it just an unrelated part of chromium?

So, how protected is the source code built with this module? What would the user have to do in order to access it? Is it baked in the .exe somehow or hidden somewhere on the disk?

**Comment by kessler** [comment]
@oL-web Sorry for the late response. This question is better suited for the nwjs team to answer. Before you post it there though, I suggest you go over this wiki article: https://github.com/nwjs/nw.js/wiki/protect-javascript-source-code-with-v8-snapshot
