### ISSUE TITLE
Windows icon (win ico) does not get applied to desktop icon after install, only default nwjs icon does

### ISSUE THREAD

**Issue by mhunter1127** [nwjs-community/nw-builder#495]
Hello,

I have tried for many different hours, and many different configurations to get my win.ico icon to apply to the desktop icon of the program I have created and installed on my mac, but using a parallels (virtual windows machine).

I am using one of the latest versions of nwjs, nwbuilder, and Inno Setup Compiler to compile the nwjs package into an .exe. Each time the default nwjs icon gets used instead of the icon that I have configured in the manifest, and in the Inno Setup Compiler.

I've also tried to use wine, and resource hacker, but the icon never gets changed on the desktop once the app is installed. 

Can you please help steer me in the right direction or ask me some questions that would get me to some positive ground?

Build command:
nwbuild -o './../build/'$1 '.' --zip false --win icon.ico -p win64,win32 -v 0.31.3

Here's the manifest contents (icon is the name of the windows icon file):
{
  "name": "My_App",
  "main": "index.html",
  "version": "1.0.0",
  "window": {
    "title": "My_App",
[github - Read me for app creation.txt](https://github.com/nwjs-community/nw-builder/files/2168335/github.-.Read.me.for.app.creation.txt)

    "show": true,
    "frame": true,
    "position": "center",
    "width": 1280,
    "height": 1000,
    "fullscreen":false,
    "toolbar":false,
    "icon": "./icon.ico"
  },
  "chromium-args": " --disk-cache-size=1 --media-cache-size=1 --incognito"
}

**Comment by mhunter1127** [comment]
Hi, 

Never got a response on this issue, so I'm just wondering if there's anybody out there who can help?

**Comment by cumtRobin** [comment]
i met the same problem... 

so, is there anybody who can help?

**Comment by mhunter1127** [comment]
@cumtRobin I'm not sure if there is anyone, because know one has replied yet.

Still waiting on response from lead community members...

**Comment by Blatman** [comment]
Not sure whether this is still an issue but I have been hacking around with NWB again and found -
--winIco in the command line is set as app.ico type file. This is used by winresourcer to populate the icon slots (1033) in the exe. With the present version of NWB the icons are added to the existing builtin icons (Incognito and an App) however even with the icon slots correctly populated in the exe I still had the situation where the window icon and taskbar icon were not displayed correctly (even if I manually used Resource Hacker).
The answer is that the window and taskbar icon rely on the icon file which is set in the window subfield of the package.json manifest.
eg: I set a folder called assets in the src folder (next to the manifest) and set manifest -
"icon": "assets/app.png",

If NWB is set for no zip then the resulting build folder will contain a package.nw folder which will include the package.json and assets/app.png

If NWB is set for zip then package.json and assets/app.png will be included in the built exe.

If the winIco is not specified as an argv then the file icon of the exe in the File Explorer is the default nwjs icon but the window and taskbar icons are OK (if specified correctly in manifest).

So for best results ensure --winIco is specified in argv ( .ico should be a correctly built ico file including a 256x256 size which will be placed in the first icon slot of exe by winresourcer) and specify icon in manifest (window subfield). The icon (whatever.png) needs to be placed wherever the manifest states - NWB will arrange appropriate positioning in the final build.

As a sidenote if multibuilds are done (eg: win32/win64) then icon insertion with winresourcer is flaky - I have found that separating win32 and win64 handling within NWB allows winresourcer to work robustly.

**Comment by Olliebrown** [comment]
I was experiencing very similar behavior and found out in the end, it was because Windows has the old icon cached.  After I logged out and back in to windows it showed the correct icon.  Perhaps this is something new with windows 10 but my situation was like this:

- I had generated the bundled executable once with an incorrect icon path
- This version of the exe had the default nwjs icon
- I fixed this but the icon refused to change despite everything being correct
- I logged out of windows and back in and magically it was then showing the right icon

So yeah, I think file explorer had the old icon cached somewhere and was not being smart enough to update it.  Just something other might want to try!

**Comment by kessler** [comment]
@Blatman @Olliebrown thank you for helping!
@mhunter1127 is this issue still relevant?

**Comment by hexianzhi** [comment]
在Windows 10中，我删除所有文件并重新启动计算机。 使用nw-builder重建我的项目后，它就可以了！

In windows 10,  I delete all the files and restart the computer. After rebuild my project with nw-builder, it workds !

Thanks to @Olliebrown

**Comment by maikonmatheus** [comment]
In your production package.json, just put the icon (it has to be a .png file) inside window fild, like this:

`{
    "name":"My App",
    "window":
        {
            "icon":"./icon.png"
        },
    "version":"0.0.1",
    "main":"./index.js"
}`
