### ISSUE TITLE
nwbuilder failed

### ISSUE THREAD

**Issue by allawitte** [nwjs-community/nw-builder#499]
I do "$  nwbuild ./ -p win32,win64,osx32,osx64,linux32,linux64"  and get an error:  "Downloading: http://dl.nwjs.io/v0.32.2/nwjs-v0.32.2-linux-x64.tar.gz
ERROR: The version 0.32.2 does not have a corresponding build posted at http://dl.nwjs.io/. Please choose a version from that list.
Unable to download nodewebkit."  - what is strange, I see this file. What can I do? I do not use gulp or grunt for this project

**Comment by kessler** [comment]
@allawitte what node version are you using? (`node --version`)

**Comment by allawitte** [comment]
The last, 8 or 9
Why?
Alla 


Web-site: http//allawitte.nl

 

----- Reply to message -----
Subject: Re: [nwjs-community/nw-builder] nwbuilder failed (#499)
Date: 18 декабря 2018 г., 19:39:42

**Comment by kessler** [comment]
@allawitte I am unable to recreate this. Downloading the file using nw-builder for v0.32.2 works perfectly fine for me. I trust you tried another version? can you provide any more details?

**Comment by ayushmxn** [comment]
@allawitte let me know if this happens in Node version 14 and above.
