### ISSUE TITLE
How to open new window on production build?

### ISSUE THREAD

**Issue by 4EPHblN** [nwjs-community/nw-builder#503]
Hi all!! 
I need to open a new window to preview the document before print it.

I using the Router to separate requests by its paths:
```html
    <Router>
        <Suspense fallback={''}>
            <Switch>
                <Print path="/print/:thingId" />
                < . . . >
                <App default />
            </Switch>
        </Suspense>
    </Router>
```

I try to open a new window through ` nw.Window.open() ` and ` <Link /> ` component from ` react-router-dom ` module.

When i use _next code_ on DEVELOPMENT build thats works as was expected: window are opens and loads the content.
```js
nw.Window.open(nw.Window.get().window.location.origin + '/print/123');
```
```html
<Link to={'/print/123'} target="_blank">Print this!!</Link>
```

But on PRODUCTION build this shows **404 Not Found** page. 

**How i can open a new window on PRODUCTION build??**

**Comment by 4EPHblN** [comment]
Are you answered me after three years?? Seriously??😅

**Comment by ayushmxn** [comment]
Lol I'm pretty new, took over maintainance of the project a few days ago.
