### ISSUE TITLE
npm install nw-builder -g not working

### ISSUE THREAD

**Issue by KasperHovlandRasmussen** [nwjs-community/nw-builder#507]
I'm trying to install nw-builder: 

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/adam-lynch/node-temp.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.

**Comment by Drugspirta** [comment]
Same issue here!

**Comment by elmz** [comment]
mine works after installing git
https://gitforwindows.org/
