### ISSUE TITLE
wine not found

### ISSUE THREAD

**Issue by indexofrefraction** [nwjs-community/nw-builder#510]
please clarify (and update the main page) on 
**how to install wine to work with nwbuild**

i am on macos and have wine installed (and working) with
_brew install wine_

still nwbuild can not use wine:
_Error while updating the Windows icon. 
Wine (winehq.org) must be installed to add custom icons from Mac and Linux._

**Comment by indexofrefraction** [comment]
i tried to add these:
npm install wine --save-dev
npm install winresourcer --save-dev

but that does not fix the problem

**Comment by Blatman** [comment]
I agree that info regarding the WINE functions of NWB are a bit thin however this may help -
Winresourcer.js (part of the NWB node_modules) is looking for "wine" in the MacOS path
67 //	  exec = "wine";
68		exec = "/Applications/Wine.app/Contents/Resources/wine/bin/wine";  //blat

I haven't tried the homebrew install of wine so not sure what it puts in the path. For my own use I have just done the standard wine dmg install to the Applications folder and then hacked the exec path ( as above) in Winresourcer.js - the dmg install does not appear to edit the MacOS path at all. I suspect you could use the homebrew install path in the same manner and it should work (at least until MacOS ceases 32bit support).

**Comment by DualWield** [comment]
+1

**Comment by ayushmxn** [comment]
@indexofrefraction Let me know if this issue still happens.
