### ISSUE TITLE
Unable to run build with nwjc protected bin

### ISSUE THREAD

**Issue by rohan-deshpande** [nwjs-community/nw-builder#518]
So, I have a directory, `files`, the contents look like this

```
static/
  bin/
    app.bin
  css/ 
    app.css
  js/
    app.js 
index.html
package.json    
```

My `index.html` looks like this 

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1,shrink-to-fit=no"
    />
    <meta name="theme-color" content="#000000" />
    <meta name="google" content="notranslate" />
    <meta http-equiv="Content-Language" content="en_US" />
    <link rel="manifest" href="/manifest.json" />
    <title>App</title>
    <link href="/static/css/app.css" rel="stylesheet" />
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <main id="root"></main>
    <script src="/static/js/app.js"></script>
  </body>
</html>
```

`app.js` like this 

```javascript
nw.Window.get().evalNWBin(null, './static/bin/app.bin');
```

If I `cd files` into this directory and run 

```
../node_modules/nw .
```

NWJS opens the app correctly and everything works. However, after building with `nw-builder` I cannot open the built app, it quits immediately. If I go into the package contents and run the `MacOS/nwjs` app in the terminal, I see an error 

```
Received signal 11 SEGV_MAPERR 000000000000
 [0x00010c37efff]
 [0x00010c37ef11]
 [0x7fff7995db5d]
 [0x7fffb00ed000]
 [0x00010b80440c]
 [0x00010b7fe547]
 [0x00010b232348]
 [0x00010b15572e]
 [0x00011035bf63]
 [0x00010bc4d472]
 [0x00010b1d2cbf]
 [0x00010b1d2221]
 [0x00010b1d1923]
 [0x00010ba510cb]
[end of stack trace]
[0616/165407.455232:WARNING:system_snapshot_mac.cc(42)] sysctlbyname kern.nx: No such file or directory (2)
logout
```

I am not sure which file was not able to found. If I do not use `nwjc` and simply leave `app.js` as the full compiled source, the built `nw-builder` app works totally fine. 

Any ideas?

**Comment by Blatman** [comment]
Tried the nwjc  with 0.38.4 on MacOS 10.13.6 and works OK when packaged by nw-builder.

In my case I -

Compiled app.js to app.bin using nwjc from 0.38.4 leaving app.bin in the src folder (removed app.js) and then adjusted the index.html file (in the src folder) to load the compiled js file -
old - <script src="js/app.js"></script>
new - <script src=nw.Window.get().evalNWBin(null, process.cwd()) + "/js/app.bin"></script>

Build the package using nw-builder.

Final built package then runs OK ( the initial run was slow because I don't have Dev Signing so Gatekeeper took its time verifiing but thereafter was normal speed on launch).

In the final built package the app.bin resides in the app.nw folder under Resources as app.js normally would.

Maybe this helps ...

**Comment by rohan-deshpande** [comment]
Hey thanks for this! It definitely helps me a little bit. So here's something interesting, after building _without_ `nwjc` I cannot find `app.js` in the resulting package contents, yet the app still works. 

Here's a screen of what my package contents look like

<img width="295" alt="Screen Shot 2019-06-17 at 6 29 02 am" src="https://user-images.githubusercontent.com/1079637/59569180-457a9b00-90c9-11e9-8ac5-43695fa53be0.png">

Are you saying that `app.js` should be in `Resources/`? Just fyi, when I open the app everything loads fine.

**Comment by Blatman** [comment]
app.nw in the Resources folder of the package is a folder and will contain all the source files of the app - these are copied into the package by nw-builder. The folder structure of app.nw should resemble your apps source structure (package.json, index.html, node_modules folder, etc). Within that folder will normally reside the app.js but if compilation is being used it should contain app.bin

**Comment by rohan-deshpande** [comment]
`Resources/app.nw` doesn't seem to be a folder though, MacOS tells me it is a `Document` file type 😭

**Comment by rohan-deshpande** [comment]
Hmm maybe the file is being compressed somehow. If I check https://github.com/nwjs-community/nw-builder/blob/5922d97cbbe80056ad735d138e0433893f6304da/test/utils.js I can see a test on line `142` which indicates this. I have `shouldZip: true` in my options so I will disable this and try again.

**Comment by Blatman** [comment]
Maybe in this case the app.nw is actually a zipped folder - usually OSX builds are made with no zipping and app.nw will be an unzipped folder but depending on the version of nw-builder maczip may be set so app.nw will be zipped - I found a bit of an anomaly with the zipping code in nw-builder when building both osx and win  so macZip needed to be false.

**Comment by rohan-deshpande** [comment]
> nw.Window.get().evalNWBin(null, process.cwd()) + "/js/app.bin"

Is this correct? Should the string concat be `process.cwd() +  "/js/app.bin"`?

**Comment by Blatman** [comment]
I just happened to use this method but variations may work

<script src=nw.Window.get().evalNWBin(null, process.cwd()) + "/js/app.bin"> works
maybe <script src=nw.Window.get().evalNWBin(null, "./js/app.bin")> would work, not sure.
The evalNWBin function is done on the loading of the bin file not from within.

**Comment by rohan-deshpande** [comment]
Okay, have just done an experiment. If I build and leave `app.js` as is and do not attempt to boot via `evalNWBin` everything works fine. I am still creating `app.bin` however, so I went into `Contents/Resources/app.nw/index.html` and simply changed the script tag to 

```html 
<script>
  nw.Window.get().evalNWBin(null, "./static/bin/app.bin");
</script>
```

I get the same error 

```
[0617/073922.275894:WARNING:system_snapshot_mac.cc(42)] sysctlbyname kern.nx: No such file or directory (2)
```

And cannot boot the app. I am wondering if this has something to do with me using a `splash.html` file for a splash page before the app fully boots, this has no issues when using the `app.js` file though and furthermore is not an issue when going into my `files` directory and running with `nw` via `../node_modules/nw .`

Really stumped here...

**Comment by Blatman** [comment]
Hitting sack - need to play tomorrow

**Comment by rohan-deshpande** [comment]
Have removed the splash page code to test things out, doesn't seem to help

```
[0617/085950.340201:WARNING:process_memory_mac.cc(93)] mach_vm_read(0x7ffeef25e000, 0x2000): (os/kern) invalid address (1)
[0617/085950.434337:WARNING:system_snapshot_mac.cc(42)] sysctlbyname kern.nx: No such file or directory (2)
```

**Comment by rohan-deshpande** [comment]
Okay, I think I know what's going on, can't try the fix right now but these words from your post pointed me in the right direction

> Compiled app.js to app.bin using nwjc from 0.38.4

I just realised there is a version mismatch between my node_modules/nw version and the version I am building with! Will try it out asap.

**Comment by Blatman** [comment]
Yes I used the nwjc from the same build that I used for the app and quite right I had a misplaced ) in the comments above - too long since I messed about with this compiling stuff since I don't use it myself.

**Comment by rohan-deshpande** [comment]
Okay, this is resolved. Was caused by not using matching NWJS versions for builds and running the nwjc command. Thanks for all your help @Blatman!
