### ISSUE TITLE
Is this package supported?

### ISSUE THREAD

**Issue by jssuttles** [nwjs-community/nw-builder#548]
The last release was 3 years ago. NW.js continues to be developed, while this important and useful package remains stagnant and starts to build up vulnerabilities and deprecations.
Are there alternatives?

**Comment by ayushmxn** [comment]
Hi, new maintainer here. That's the plan - triage issues and pull requests and go from there. Realistically, it'll probably take me ~2 weeks to get the next release out.

**Comment by jssuttles** [comment]
That's great!!! Thanks!
