### ISSUE TITLE
Platform based plugin copying

### ISSUE THREAD

**Issue by Rameshv** [nwjs-community/nw-builder#87]
Hi
   Currently all files in `app/plugin` folder are are copied to all different builds. Instead it should only copy the plugin files relevant to the platform. Currently i am shipping my builds (`mac/windows`) with flashplayer (`Flash Player.plugin & pepflashplayer.dll`). when running the deploy build, i got these both the files copied to both the builds. This is unnecessary, and end up taking more space than expected.

Is there any way to copy the plugin files on conditional basis?. If there isn't any existing approach, i would like to make a patch? 

Please let me know

**Comment by vikbez** [comment]
I would like this too. :+1:
