### ISSUE TITLE
Run

### ISSUE THREAD

**Issue by adam-lynch** [nwjs-community/nw-builder#98]
The run feature isn't documented well enough or tested at all. 

The documentation only quickly mentions it as a command-line option but doesn't say what it actually does (my assumption is that you'd use it instead of [shama/nodewebkit](https://github.com/shama/nodewebkit)?). There is no mention of using run programmatically (e.g. `nwBuilder.run()`).

For me, I just tried it there on Windows 8.1 and it worked _once_. Any time I try to run it since, the app exits quickly with code `0`. On my Mac, it works continuously.

**Comment by adam-lynch** [comment]
How about we remove the `run` option altogether? I don't think people come to node-webkit- *builder* looking for a solution for running the app in dev. 

I think it makes sense to remove it now especially because [nwjs is going to have an official npm module](https://github.com/shama/nodewebkit/issues/57#issuecomment-70125621) (so people would use that in dev).

I think it would reduce the amount of code we have, make the documentation and purpose clearer, etc.

Let me know if there's any major reason why we shouldn't or anything that people can do with `run` which users would lose if they switched to the official npm package instead.

The only thing I can think of is that if you used the official npm package for dev and this for building, you would be downloading one version of nwjs with the official module and then one per platform with ours. I don't think it's a huge deal though and we could probably optimize it to check if the official module is installed or something like that. Or maybe we could have a common module for downloading & caching nwjs versions, then both this module and the nwjs one could use it.

**Comment by adam-lynch** [comment]
cc @steffenmllr @trevorah @dylangattey @gabepaez

**Comment by steffenmllr** [comment]
Thats ok with me. If anybody is contact with rogerwang we could ask hin if the builder and the grunt module come somewhat offical and under the `nwjs` github repo.

**Comment by trevorah** [comment]
I totally agree with dropping `run()`. We should probably deprecate it now in the readme and then drop it in 2.0.0.

**Comment by kessler** [comment]
Hi guys

Sorry I cam into this thread late.

Here is an example to a project that does use run() for dev purposes, programmatically: https://github.com/kessler/nw-ninja

The gulp tasks that are provided with this nw.js starter project rely on the fact that run() invokes most or some of the prelogic that is used in build(). Of course this can be implemented with another package and then grouped under a gulp task that will build() using node-webkit-builder and run using whatnot but is this the right approach?

I think that if its possible for a developer to develop using a one version and build a distribution using another then it will probably happen somewhere and that it is a huge deal. I can already imagine the post mortem discussion taking place somewhere in the world where a dev team didn't have the right precautions to prevent something like this from happening.

Speaking of precautions, adding code to node-webkit-builder that checks if npm-installer is there, if nw.js files were downloaded and what is the version will probably create a strong coupling between the two modules, too strong in my opinion.

After writing all of this it is suddenly dawned on me that node-webkit-builder and npm-installer are very much a like and should unite. I think that the common module Adam suggested will in fact be this union. Until that happens though I suggest that both modules will "stay away from each other" sort of speak and that the run() functionality will be maintained.

**Comment by kessler** [comment]
p.s I forgot to say I'm in contact with Roger occasionally via email and skype, don't know if you approached him with this already but if you didn't and still want to please let me know

**Comment by kessler** [comment]
@adam-lynch is there a point to reopen this issue/discussion?

**Comment by adam-lynch** [comment]
> Speaking of precautions, adding code to node-webkit-builder that checks if npm-installer is there, if nw.js files were downloaded and what is the version will probably create a strong coupling between the two modules, too strong in my opinion.

Maybe both modules could depend on a common module for downloading & caching?

>After writing all of this it is suddenly dawned on me that node-webkit-builder and npm-installer are very much a like and should unite. I think that the common module Adam suggested will in fact be this union. Until that happens though I suggest that both modules will "stay away from each other" sort of speak and that the run() functionality will be maintained.


Oh ok, yeah, I don't think we were going to remove run() before we have the common one.

**Comment by Blatman** [comment]
This discussion is probably dead in the water now but from my point of view having the run function in nwb is excellent - it allows me to run the target app from the source folder without a copy of nwjs residing in it because nwb will use the version specified in the build options using the cache builds.
Also by altering the build options the app can easily be run on different versions.
It works so no point in removing at the expense of spending time on other features/bugs.
Cheers.
